site_name: My Blog

site_url: https://MY_NAME.github.io/MY_BLOG

site_author: MY_NAME

site_description: My blog made with Material for MkDocs

repo_name: MY_NAME/MY_BLOG

repo_url: https://github.com/MY_NAME/MY_BLOG

copyright: Copyright &copy; 2025 - 2025 MY_NAME


theme:

  name: material

  custom_dir: overrides

  language: en

  favicon: assets/favicon.png

  icon:
    logo: material/library

  features:
  - content.code.copy
  - navigation.footer
  - navigation.indexes
  # - navigation.instant
  - navigation.sections
  # - navigation.tabs
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.suggest
  - toc.follow

  palette:
  # State: Light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: 'Light to Dark'
    primary: indigo
    accent: indigo
  # State: Dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/brightness-3
      name: 'Dark to Light'
    primary: black
    accent: indigo


extra:

  social:
  - icon: fontawesome/brands/github
    link: 'https://github.com/MY_NAME'


plugins:

- blog:
    archive_date_format: yyyy
    archive_url_date_format: yyyy
    archive_url_format: "archive/{date}"
    authors: true
    blog_dir: .
    categories_url_format: "category/{slug}"
    pagination_format: "$link_first ~2~ $link_last"
    pagination_per_page: 10
    pagination_url_format: "page/{page}"
    post_date_format: long
    post_excerpt: required
    post_readtime: true
    post_url_date_format: yyyy-MM-dd
    post_url_format: "{date}/{slug}"

- meta

- search

- tags


markdown_extensions:

# Python Markdown

- admonition

- attr_list

- footnotes

- md_in_html

- sane_lists

- toc:
    permalink: true
    title: Table of Contents
    toc_depth: 3

# Python Markdown Extensions

- pymdownx.arithmatex:
    generic: true

- pymdownx.betterem:
    smart_enable: all

- pymdownx.caret

- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg

- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true

- pymdownx.inlinehilite

- pymdownx.mark

- pymdownx.superfences

- pymdownx.tabbed:
    alternate_style: true

- pymdownx.tilde


extra_css:
- stylesheets/extra.css
- https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css


extra_javascript:
- javascripts/katex.js
- https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.js
- https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/contrib/auto-render.min.js
